"""initial schema

Revision ID: 5be1ec17bac5
Revises: 
Create Date: 2026-08-24 21:43:00.000082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5be1ec17bac5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_borrower_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending_docs', 'processing', 'manual_review', 'ready_for_los', name='application_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_borrower_status_created', 'applications', ['external_borrower_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_external_borrower_id'), 'applications', ['external_borrower_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('llm_prompt', sa.Text(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=7), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_application_created', 'audit_logs', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_application_id'), 'audit_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'email', name='communication_channel'), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='communication_direction'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_application_id'), 'communications', ['application_id'], unique=False)
    op.create_index('ix_communications_application_timestamp', 'communications', ['application_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_communications_created_at'), 'communications', ['created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('s3_path', sa.String(length=1024), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_application_id'), 'documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_documents_content_sha256'), 'documents', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IS NULL OR source_snippet IS NOT NULL', name='ck_extracted_facts_source_integrity'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_facts_application_id'), 'extracted_facts', ['application_id'], unique=False)
    op.create_index('ix_extracted_facts_application_key', 'extracted_facts', ['application_id', 'key'], unique=False)
    op.create_index(op.f('ix_extracted_facts_created_at'), 'extracted_facts', ['created_at'], unique=False)
    op.create_index(op.f('ix_extracted_facts_document_id'), 'extracted_facts', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_facts_document_id'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_created_at'), table_name='extracted_facts')
    op.drop_index('ix_extracted_facts_application_key', table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_application_id'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_application_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_communications_created_at'), table_name='communications')
    op.drop_index('ix_communications_application_timestamp', table_name='communications')
    op.drop_index(op.f('ix_communications_application_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_application_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_application_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_external_borrower_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_index('ix_applications_borrower_status_created', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
