"""add idempotency_key to communications

Revision ID: a23786e1b368
Revises: 5be1ec17bac5
Create Date: 2026-08-24 23:46:29.444419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a23786e1b368'
down_revision: Union[str, Sequence[str], None] = '5be1ec17bac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communications', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.alter_column('communications', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.create_index(op.f('ix_communications_idempotency_key'), 'communications', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communications_idempotency_key'), table_name='communications')
    op.alter_column('communications', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-24 16:13:15.172927+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_column('communications', 'idempotency_key')
    # ### end Alembic commands ###
